name: Rocket League Player Stats API Continuous Deployment Pipeline

on:
  push:
    branches: [main]
jobs:
  export_bundled_api_as_zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Clean install npm dependencies
        run: npm ci
      - name: Build nestjs project
        run: npm run build
      - name: Show folder contents
        run: |
          echo "Checked out repository content:"
          ls -al
      - name: Zip dist folder
        run: |
          echo "Bundled content:"
          cd dist/
          tar -czf /tmp/bundled-api.tar.gz .
          ls
      - name: Save zip for next job
        uses: actions/upload-artifact@v2
        with:
          name: bundled-api
          path: /tmp/bundled-api.tar.gz
  upload_zipped_api_bundle:
    needs: export_bundled_api_as_zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download zipped bundled api
        uses: actions/download-artifact@v2
        with:
          name: bundled-api
      - name: Create ssh key
        run: |
          mkdir -p ~/.ssh/
          echo ${{ secrets.PRIVATE_KEY }} > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
      - name: Save old api as zip in backup folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            DATE=`date '+%d-%m-%y_%H-%M-%S'`
            BACKUP_FILENAME=rl_player_stats_$DATE.tar.gz
            cd /home/tilloh/api/rl_player_stats
            tar -czf /home/tilloh/api/backup/$BACKUP_FILENAME .
            rm -r /home/tilloh/api/rl_player_stats/*
      - name: Deploy zipped website via scp
        uses: horochx/deploy-via-scp@master
        with:
          local: bundled-api.tar.gz
          remote: /home/tilloh/api/rl_player_stats
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
      - name: Unzip new website version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/tilloh/api/rl_player_stats
            tar -zxf bundled-api.tar.gz
            rm bundled-api.tar.gz